
title: Sugar Foot!
email: 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Dances section 
#---------------------------

lindyDesc: The Lindy hop is an American dance which was born in Harlem, New York City in 1928. <br/>
           In its development, the Lindy hop combined elements of both partnered and solo dancing by using the movements, and improvisation of African-American dances along with the formal eight-count structure of European partner dances. <br/>
           Lindy hop is sometimes referred to as a street dance, referring to its improvisational and social nature.
shagDesc: The Collegiate Shag (or "Shag") is a partner dance done primarily to uptempo swing. <br/>
          It belongs to the swing family of American vernacular dances that arose in the 1920s and 30s. It is believed that the dance originated within the African American community[1] of the Carolinas in the 1920s, later spreading across the United States during the 1930s. <br/>
          Because the basic step takes up such a small space, the Shag can also be danced to fast music.
bluesDesc: Blues dancing is a family of historical dances that developed alongside and were danced to blues music, or the contemporary dances that are danced in that aesthetic. <br/>
           There are now blues dancing communities throughout the international swing dancing community, though local communities vary, reflecting local social and cultural values and contexts. The spread of blues dancing has been largely a result of individual dancers traveling between local communities and establishing blues scenes.


copyRight: Copyright 2018
footerText: Sugar Foot!